name: zycloud_widget
description: This library contains a dynamic Flutter widget module based on the shelf_easy virtual machine, and some third-party library bridge generation modules.
version: 1.0.18
homepage: https://github.com/yangfanyu/zycloud_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  shelf_easy: ^3.0.0
  zycloud_client: ^1.0.0
  pubspec_lock: ^3.0.0

  # -------- Below plugins full support [all] platforms --------  
  # common
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  platform_device_id: ^1.0.0
  hive: ^2.2.0
  image: ^4.0.0
  file_picker: ^5.3.0
  extended_image: ^8.0.0
  pretty_qr_code: ^2.0.0
  overlay_support: ^2.1.0
  # extend_full
  audioplayers: ^5.1.0
  flutter_linkify: ^6.0.0
  flutter_slidable: ^3.0.0
  flutter_vector_icons: ^2.0.0
  flutter_webrtc: ^0.9.0
  loading_indicator: ^3.1.0
  scrollable_positioned_list: ^0.3.0
  url_launcher: ^6.1.0
  # extend_full_depend
  audioplayers_platform_interface: ^6.0.0
  linkify: ^5.0.0
  webrtc_interface: ^1.0.0
  # -------- Below plugins only support [android, ios, windows] platform --------    
  # extend_part
  permission_handler: ^10.2.0
  # extend_part_depend
  permission_handler_platform_interface: ^3.9.0
  # -------- Below plugins only support [android, ios] platform --------    
  # extend_part
  webview_flutter: ^4.2.0
  webview_flutter_android: ^3.6.0
  webview_flutter_wkwebview: ^3.4.0
  # extend_part_depend
  webview_flutter_platform_interface: ^2.3.0
  # -------- Below plugins only support [android, ios, linux, macos, windows] platform --------  
  # common
  path_provider: ^2.0.0
  # -------- Below plugins only support [android, ios, linux, macos] platform --------    
  # common
  flutter_local_notifications: ^15.1.0
  # -------- Below plugins only support [android, ios, macos, web] platform --------    
  # common
  qr_code_scanner: ^1.0.0
  # -------- Below plugins only support [android, ios, web] platform --------  
  # common
  image_picker: ^1.0.0
  # -------- Below plugins only support [android, ios] platform --------  
  # common
  move_to_background: ^1.0.0
  # -------- Below plugins only support [android] platform --------  
  # common
  flutter_background: ^1.2.0
  # -------- Below plugins full support [all] platforms, but pub.dev only show [ios, linux, macos, windows] platform--------  
  # common
  flutter_quill: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: zycloud_widget
      ios:
        default_package: zycloud_widget
      linux:
        default_package: zycloud_widget
      macos:
        default_package: zycloud_widget
      windows:
        default_package: zycloud_widget
      web:
        default_package: zycloud_widget

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
